# ekf.yaml
ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.2  # 增加传感器超时时间
    two_d_mode: true  # 如果机器人只在二维平面上运动，设置为true
    transform_time_offset: 0.0
    transform_timeout: 0.3  # 进一步增加变换超时时间
    print_diagnostics: true
    debug: false
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # 轮式编码器 (odom0)
    odom0: odom/wheel
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 2
    odom0_nodelay: true
    odom0_differential: false  # 使用绝对值
    odom0_relative: false

    # 激光里程计 (odom1)
    odom1: odom/laser
    odom1_config: [true, true, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom1_queue_size: 2
    odom1_nodelay: true
    odom1_differential: false  # 使用绝对值
    odom1_relative: false

    # IMU (可选)
#     imu0: imu/data
#     imu0_config: [false, false, false,
#                   true, true, true,
#                   false, false, false,
#                   true, true, true,
#                   true, true, true]
#     imu0_nodelay: false
#     imu0_differential: false
#     imu0_relative: false
#     imu0_queue_size: 5
#     imu0_remove_gravitational_acceleration: true